# Generated by Django 5.0.14 on 2026-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.TextField(blank=True, help_text='Contact person, email, phone, etc.')),
                ('rate', models.CharField(blank=True, help_text='e.g. hourly rate or monthly fee', max_length=100)),
                ('projects_done', models.TextField(blank=True, help_text='Projects we have delivered for them')),
                ('potential_needs', models.TextField(blank=True, help_text='What we think they might need next')),
                ('known_issues', models.TextField(blank=True, help_text='Problems we are aware of')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
